### ISSUE TITLE
vercel: Could not load the "sharp" module using the linux-x64 runtime

### ISSUE THREAD

**Issue by latiosu** [PlayForm/Compress#252]
**Issue:** When using `astro-compress` in the context of a Vercel build (linux-x64 runtime), the sharp binary is not being found causing a failure to import `astro-compress`.

**Version affected:** `2.2.5`

**Screenshot of issue:**
![image](https://github.com/astro-community/AstroCompress/assets/7020503/e8051655-abc9-4b52-909e-7a96e05d06cf)

**Workaround:**
Downgrade `astro-compress` to `2.2.3` which uses a working version of `sharp` (`0.32.6`) ([reference](https://github.com/astro-community/AstroCompress/blame/44d0b805757232c81c851ee0fed7639512cb4dd5/package.json))
```
// package.json
{
  "dependencies": {
    "astro-compress": "2.2.3",
    "typescript": "~5.2.2"
  }
}
```
![image](https://github.com/astro-community/AstroCompress/assets/7020503/9b91d5e8-a72e-4672-93a7-f52b3743a714)

Related issues:
- https://github.com/vercel/nft/issues/371
- https://github.com/lovell/sharp/issues/3870

**Comment by NikolaRHristov** [comment]
Hi, can you maybe try using the [#no-sharp](https://github.com/astro-community/AstroCompress/tree/no-sharp) branch like in: https://github.com/astro-community/AstroCompress/issues/200 or checking if `overrides:` in your `package.json` fixes it like in: https://github.com/astro-community/AstroCompress/issues/244

**Comment by gitZokki** [comment]
Try add this to your package.json (maybe change the version)
`
"resolutions": {
	"astro/sharp": "0.33.0",
	"astro-compress/sharp": "0.33.0"
}`

**Comment by NikolaRHristov** [comment]
> Try add this to your package.json (maybe change the version) ` "resolutions": { "astro/sharp": "0.33.0", "astro-compress/sharp": "0.33.0" }`

`"resolutions"` is specific to Yarn https://yarnpkg.com/configuration/manifest#resolutions use `"overrides"` for both NPM and Yarn:

```json
{
  "overrides": {
    "astro": {
      "sharp": "0.33.0"
    }
  }
}
```

**Comment by nikitaprokopov** [comment]
> > Try add this to your package.json (maybe change the version) ` "resolutions": { "astro/sharp": "0.33.0", "astro-compress/sharp": "0.33.0" }`
> 
> `"resolutions"` is specific to Yarn https://yarnpkg.com/configuration/manifest#resolutions use `"overrides"` for both NPM / PNPM and Yarn:
> 
> ```json
> {
>   "overrides": {
>     "astro": {
>       "sharp": "0.33.0"
>     }
>   }
> }
> ```

Doesn't work for me

**Comment by NikolaRHristov** [comment]
> > > Try add this to your package.json (maybe change the version) ` "resolutions": { "astro/sharp": "0.33.0", "astro-compress/sharp": "0.33.0" }`
> > 
> > 
> > `"resolutions"` is specific to Yarn [yarnpkg.com/configuration/manifest#resolutions](https://yarnpkg.com/configuration/manifest#resolutions) use `"overrides"` for both NPM / PNPM and Yarn:
> > ```json
> > {
> >   "overrides": {
> >     "astro": {
> >       "sharp": "0.33.0"
> >     }
> >   }
> > }
> > ```
> 
> Doesn't work for me

What is the output of `npm ls sharp` inside your project?

**Comment by nikitaprokopov** [comment]
This worked for me:  
```
  "overrides": {
    "react": "npm:@preact/compat@latest",
    "react-dom": "npm:@preact/compat@latest",
    "astro": {
      "sharp": "0.32.6"
    },
    "astro-compress": {
      "sharp": "0.32.6"
    }
  }
```

But I have another error:
![image](https://github.com/astro-community/AstroCompress/assets/154567949/4b88d73d-7ae9-4012-96d1-5b6727584738)

My package.json:  
```
{
  "name": "arch-capital-landing",
  "type": "module",
  "version": "0.0.1",
  "scripts": {
    "dev": "astro dev --host",
    "start": "astro dev --host",
    "build": "astro build",
    "preview": "astro preview",
    "astro": "astro",
    "tsm:watch": "typed-scss-modules ./src/**/*.module.scss -p.$ src --watch"
  },
  "dependencies": {
    "@astrojs/preact": "^3.0.2",
    "@floating-ui/react": "^0.26.4",
    "@fontsource/inter": "^5.0.16",
    "@fontsource/playfair-display": "^5.0.18",
    "@fontsource/roboto": "^5.0.8",
    "astro": "^4.0.9",
    "astro-compress": "^2.2.5",
    "astro-critters": "^2.0.11",
    "framer-motion": "^10.17.4",
    "modern-normalize": "^2.0.0",
    "preact": "^10.19.3",
    "swiper": "^11.0.5",
    "typescript": "^5.3.3"
  },
  "devDependencies": {
    "@typescript-eslint/parser": "^6.17.0",
    "autoprefixer": "^10.4.16",
    "cssnano": "^6.0.2",
    "eslint": "^8.56.0",
    "eslint-config-prettier": "^9.1.0",
    "eslint-plugin-astro": "^0.31.0",
    "eslint-plugin-jsx-a11y": "^6.8.0",
    "eslint-plugin-perfectionist": "^2.5.0",
    "eslint-plugin-promise": "^6.1.1",
    "eslint-plugin-react": "^7.33.2",
    "eslint-plugin-react-hooks": "^4.6.0",
    "eslint-plugin-sonarjs": "^0.23.0",
    "eslint-plugin-unicorn": "^50.0.1",
    "prettier": "^3.1.1",
    "sass": "^1.69.7",
    "stylelint": "^16.1.0",
    "stylelint-config-recess-order": "^4.4.0",
    "stylelint-config-standard-scss": "^12.0.0",
    "vite-plugin-optimize-css-modules": "^1.0.6"
  },
  "overrides": {
    "react": "npm:@preact/compat@latest",
    "react-dom": "npm:@preact/compat@latest",
    "astro": {
      "sharp": "0.32.6"
    },
    "astro-compress": {
      "sharp": "0.32.6"
    }
  }
}
```

**Comment by nikitaprokopov** [comment]
> npm ls sharp

![image](https://github.com/astro-community/AstroCompress/assets/154567949/d68fb281-290e-4b29-a683-2938e9261dd4)

**Comment by nikitaprokopov** [comment]
> [#no-sharp](https://github.com/astro-community/AstroCompress/tree/no-sharp)

Could you explain how to switch to [#no-sharp](https://github.com/astro-community/AstroCompress/tree/no-sharp)? I want to try it but don't understand how

**Comment by nikitaprokopov** [comment]
> > [#no-sharp](https://github.com/astro-community/AstroCompress/tree/no-sharp)
> 
> Could you explain please how to switch to [#no-sharp](https://github.com/astro-community/AstroCompress/tree/no-sharp)? I want to try it but don't understand how

Do this with `npm i https://github.com/astro-community/AstroCompress.git#no-sharp -D`. Is this correct?

**Comment by NikolaRHristov** [comment]
@nikitaprokopov You can install it like so:

```sh
npm install -D -E astro-community/AstroCompress#no-sharp
```

**Comment by NikolaRHristov** [comment]
Should be fixed in the latest [v2.2.7](https://github.com/astro-community/AstroCompress/releases/tag/v2.2.7) which uses the latest `sharp` at the time `0.33.1` the same as `Astro`'s `0.33.1`

**Comment by Wolfleader101** [comment]
Hi,

This still seems like its an issue even with the latest version of astro-compress `2.2.10` is there any way around it?

**Comment by zokkis** [comment]
> Hi,
> 
> This still seems like its an issue even with the latest version of astro-compress `2.2.10` is there any way around it?

Add "astro-compress": "astro-community/AstroCompress#no-sharp" instead of "astro-compress": "^2.2.10"

**Comment by NikolaRHristov** [comment]
Will be fixed in https://github.com/Playform/Compress/issues/329. You can track that issue there.

**Comment by davidawad** [comment]
I still have this issue for what it's worth in all of my astro sites when I deploy templates from vercel.

**Comment by NikolaRHristov** [comment]
@davidawad Can you provide a bit more information on how you're running it ? What version are you using, is it the latest `astro` + `astro-compress` or `@playform/compress` I'm trying it on https://github.com/NikolaRHristov/Starter and it runs / builds successfully - https://github.com/NikolaRHristov/Starter/commit/7ab86cfe0c55c40e74b46d41293892a07bad00e4#commitcomment-142393730

![image](https://github.com/PlayForm/Compress/assets/90222871/c6a8df7e-c7c2-46d2-be49-e834f9ed50d6)

**Comment by davidawad** [comment]
This was a while ago and was able to fix it but never figured out how

I can tell you that when using latest sharp this breaks. I ran into it on 4 different Astro websites deployed on vercel. 

I *think* the issue Was solved going down to sharp 32.4.

**Comment by NikolaRHristov** [comment]
@davidawad Have you tried the resolutions hotfix in `package.json` https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides

Like this:

```json
"overrides": {
	"astro": {
		"sharp": "0.32.6"
	},
	"astro-compress": {
		"sharp": "0.32.6"
	}
}
```
